"""Models and database functions for gigaware

Revision ID: fc9ad74f38f6
Revises: None
Create Date: 2016-01-29 15:01:35.311927

"""

# revision identifiers, used by Alembic.
revision = 'ad17315dd1b5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

status = ENUM('pending', 'confirmed', 'rejected', name='reservation_status_enum',
                            create_type=False)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('area_code', sa.String(), nullable=False),
                    sa.Column('zip_code', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('job_listings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('zip_code', sa.Integer(), nullable=False),
                    sa.Column('details', sa.String(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('host_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reservations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.Column('status', reservation_status_enum, nullable=False),
                    sa.Column('anonymous_phone_number', sa.String(), nullable=True),
                    sa.Column('guest_id', sa.Integer(), nullable=True),
                    sa.Column('job_task_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['job_task_id'], ['job_listings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('job_listings')
    op.drop_table('users')
    ### end Alembic commands ###
